# This is a basic workflow to help you get started with Actions

name: Update README Table of Contents

on:
  push:
    branches:
      - main # Modify this to match your repository's main branch

jobs:
  update-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use Node.js version 16

      - name: Install markdown-toc
        run: npm install -g markdown-toc

      - name: Update Table of Contents
        run: markdown-toc -i README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README table of contents"
          git push
